name: Test

on:
  workflow_call:
    outputs:
      tests-passed:
        description: "Whether all tests passed"
        value: ${{ jobs.test.outputs.tests-passed }}
  workflow_dispatch:
  pull_request:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]

    outputs:
      tests-passed: ${{ steps.test-result.outputs.passed }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests (Linux)
      id: run-tests
      if: runner.os == 'Linux'
      run: xvfb-run -a npm test
      continue-on-error: true

    - name: Run tests (macOS/Windows)
      id: run-tests-other
      if: runner.os != 'Linux'
      run: npm test
      continue-on-error: true

    - name: Set test result
      id: test-result
      run: |
        OUTCOME="${{ steps.run-tests.outcome }}${{ steps.run-tests-other.outcome }}"
        if [[ "$OUTCOME" == "success" ]] || [[ "$OUTCOME" == "successskipped" ]] || [[ "$OUTCOME" == "skippedsuccess" ]]; then
          echo "passed=true" >> $GITHUB_OUTPUT
        else
          echo "passed=false" >> $GITHUB_OUTPUT
          exit 1
        fi
      shell: bash

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-node${{ matrix.node-version }}
        path: |
          coverage/
          test-workspace/
          *.log
